### ISSUE TITLE
cannot retrieve decrypted values in k8s deployment 

### ISSUE THREAD

**Issue by shreyas-shinde** [StackStorm/st2-docker#120]
Have deployed 3 replicas of each deployment
I use action service to set key,value in datastore with decrypt=true. Then when try to get that value it fails sometimes and succeeds sometimes. So encryption is mostly using some pod specific property. It fails with below error:
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/datastore.py", line 124, in get_value
    kvp = client.keys.get_by_id(id=name, params=params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 204, in get_by_id
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 166, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error

I have set env variable ST2_BASE_URL to point to correct api server url.

**Comment by armab** [comment]
Thanks for the report and sorry for a long waiting time.

We now ship ST2 K8s deployment via https://github.com/stackstorm/stackstorm-ha Helm chart.
You can use https://docs.stackstorm.com/install/k8s_ha.html which has enough documentation and support & help references.
