### ISSUE TITLE
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by vhristev** [StackStorm/st2-docker#173]
**Describe the problem**
```
root@df160368fa19:/# st2 action list
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))
```
**Versions**
 - Host OS: [MacOSX 10.14.4 (18E226) ]
 - docker: [Docker version 18.09.2, build 6247962]
 - docker-compose: [docker-compose version 1.23.2, build 1110ad01]
 - stackstorm/stackstorm image: [stackstorm/stackstorm:latest and I tried with :dev]

**To Reproduce**
```
git clone git@github.com:stackstorm/st2-docker
cd st2-docker
make env
docker-compose up -d
docker-compose exec stackstorm bash
root@df160368fa19:/# st2 action list
ERROR: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

I tried with different image versions without a luck ( latest and dev).
Solution below work for some users but not for me.
```
~/Desktop/st2-docker(master*) » cat conf/rabbitmq.env                                                                                   
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
```

**### It seems affect just OSX I tried with CentOS and its working fine:**
```

root@dd498610bb42:/# st2 pack list
+----------+----------+----------------------------------------+---------+------------------+
| ref      | name     | description                            | version | author           |
+----------+----------+----------------------------------------+---------+------------------+
| chatops  | chatops  | ChatOps integration pack               | 3.0.0   | StackStorm, Inc. |
| core     | core     | Basic core actions.                    | 3.0.0   | StackStorm, Inc. |
| default  | default  | Default pack where all resources       | 3.0.0   | StackStorm, Inc. |
|          |          | created using the API with no pack     |         |                  |
|          |          | specified get saved.                   |         |                  |
| examples | examples | Example sensors, triggers, actions and | 3.0.0   | StackStorm, Inc. |
|          |          | rules.                                 |         |                  |
| linux    | linux    | Generic Linux actions                  | 3.0.0   | StackStorm, Inc. |
| packs    | packs    | Pack management functionality.         | 3.0.0   | StackStorm, Inc. |
+----------+----------+----------------------------------------+---------+------------------+
root@dd498610bb42:/# exit
^LYou have new mail in /var/spool/mail/root
[root@RHCSA-server01 st2-docker]#
[root@RHCSA-server01 st2-docker]# docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false

[root@RHCSA-server01 st2-docker]# docker-compose version
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
[root@RHCSA-server01 st2-docker]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

**Comment by warrenvw** [comment]
Hello. I have been unable to reproduce this error on MacOS 10.12.6. I tried with both `stackstorm/stackstorm:3.0.0` and `stackstorm/stackstorm:dev` using docker `18.09.2` and docker-compose `1.23.2`.

Did you see anything specific in any logs that indicates what is the cause of that connection error? Does `st2ctl status` indicate any processes are not running?

```
$ docker-compose exec stackstorm bash
root@47240fd10429:/# st2 action list
+----------------------------------------------+----------+----------------------------------------------+
| ref                                          | pack     | description                                  |
+----------------------------------------------+----------+----------------------------------------------+
| chatops.format_execution_result              | chatops  | Format an execution result for chatops       |
| chatops.match                                | chatops  | Match a string to an action alias            |
| chatops.match_and_execute                    | chatops  | Execute a chatops string to an action alias  |
| chatops.post_message                         | chatops  | Post a message to stream for chatops         |
| chatops.post_result                          | chatops  | Post an execution result to stream for       |
...
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
$ docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Comment by vhristev** [comment]
Im not sure where is the problem. I don't see any errors / warnings in the logs. 

As I said on my linux box is working im not sure what is the cause of the issue on my Mac. 

Any clue what it could be the problem or where I can deep dive. ?  I tried ,so many different ways to make it run without success. Even purge entire docker and did everything from scratch. 

```
root@b466ef6f266f:/# st2ctl status
##### st2 components status #####
st2actionrunner PID: 98
st2actionrunner PID: 106
st2actionrunner PID: 111
st2actionrunner PID: 116
st2actionrunner PID: 120
st2actionrunner PID: 125
st2actionrunner PID: 129
st2actionrunner PID: 138
st2actionrunner PID: 144
st2actionrunner PID: 148
st2api PID: 974
st2api PID: 987
st2stream PID: 61
st2stream PID: 294
st2auth PID: 47
st2auth PID: 313
st2garbagecollector PID: 43
st2notifier PID: 51
st2resultstracker PID: 49
st2rulesengine PID: 56
st2sensorcontainer PID: 40
st2chatops is not running.
st2timersengine PID: 60
st2workflowengine PID: 52
st2scheduler PID: 1022
mistral-server PID: 415
mistral.api PID: 409
mistral.api PID: 445
mistral.api PID: 446
```

```
~/Desktop/st2-docker(master*) » docker images                                                                                                                                                                                                                  vhristev@vhristev-a01
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
mongo                   3.4                 7839dd952238        9 days ago          426MB
stackstorm/stackstorm   3.0.0               960bde6bc7e8        10 days ago         937MB
stackstorm/stackstorm   latest              960bde6bc7e8        10 days ago         937MB
postgres                9.6                 9183c04acbe8        11 days ago         230MB
redis                   4.0                 14433f4e77ab        5 weeks ago         83.4MB
rabbitmq                3.6-management      9df8e9792ce6        6 months ago        149MB


```

**Comment by LindsayHill** [comment]
> rabbitmq                3.6-management      9df8e9792ce6        6 months ago        149MB

**6 months ago**

Seems pretty old. Possibly suspicious. Worth removing & re-pulling that?

**Comment by vhristev** [comment]
If you open docker-compose.yml file and check line 46 its what they use in the docker file so I don't thing that is the problem if that was the problem it will be the same issue on Linux box. Right now I cannot understand why the Mac is not working but on linux is totally fine. 
```
45   rabbitmq:
 46     image: rabbitmq:3.6-management
 47     env_file:
```

**Comment by vhristev** [comment]
One of the things I notice is that st2-register-content process is spawn regularly which is using a lot of CPU. That process should finish and not cycling around I'm not sure why this is happening also.

```
root@52b467771560:/# ps aux | grep regi
root     35462  0.0  0.1  18116  3000 ?        S    12:36   0:00 /bin/bash /usr/bin/st2ctl reload --register-all
root     35467 80.5  3.7 328320 75728 ?        S    12:36   0:07 /opt/stackstorm/st2/bin/python /usr/bin/st2-register-content --config-file /etc/st2/st2.conf --register-all
root     35533  0.0  0.1  10476  2128 pts/1    S+   12:37   0:00 grep --color=auto regi
root@52b467771560:/# ps aux | grep regi
root     35626  0.0  0.1  10476  2128 pts/1    S+   12:37   0:00 grep --color=auto regi
root@52b467771560:/# ps aux | grep regi
root     35628  0.0  0.1  10476  2128 pts/1    S+   12:37   0:00 grep --color=auto regi
root@52b467771560:/# ps aux | grep regi
root     35634  0.0  0.1  10476  2128 pts/1    S+   12:37   0:00 grep --color=auto regi
root@52b467771560:/# ps aux | grep regi
root@52b467771560:/# ps aux | grep regi
root     35653  0.0  0.1  18116  2948 ?        S    12:37   0:00 /bin/bash /usr/bin/st2ctl reload --register-all
root     35658 69.0  2.6 138976 53660 ?        S    12:37   0:00 /opt/stackstorm/st2/bin/python /usr/bin/st2-register-content --config-file /etc/st2/st2.conf --register-all
root     35667  0.0  2.2 137948 45668 ?        R    12:37   0:00 /opt/stackstorm/st2/bin/python /usr/bin/st2-register-content --config-file /etc/st2/st2.conf --register-all
root     35669  0.0  0.1  10476  2120 pts/1    S+   12:37   0:00 grep --color=auto regi
```

That is eating my CPU and it keeps ST2

**Comment by vhristev** [comment]
Here is some output from StackStorm container and st2-docker 
[st2-docker.txt](https://github.com/StackStorm/st2-docker/files/3152676/st2-docker.txt)

**Comment by vhristev** [comment]
I think the problem is when stackstorm client connects to rabbitMQ but I don't know what is the root cause: 
It could be some OS related kernel network parameter. 

Some log output from docker-compose 
```
176 rabbitmq_1    | =WARNING REPORT==== 7-May-2019::12:44:53 ===
177 rabbitmq_1    | closing AMQP connection <0.15612.0> (172.22.0.6:48140 -> 172.22.0.3:5672, vhost: '/', user: 'guest'):
178 rabbitmq_1    | client unexpectedly closed TCP connection
179 rabbitmq_1    |
180 rabbitmq_1    | =WARNING REPORT==== 7-May-2019::12:44:53 ===
181 rabbitmq_1    | closing AMQP connection <0.15728.0> (172.22.0.6:48150 -> 172.22.0.3:5672, vhost: '/', user: 'guest'):
182 rabbitmq_1    | client unexpectedly closed TCP connection
```

**Comment by armab** [comment]
Take a look at stackstorm logs (`/var/log/st2/`), especially `st2api`.
If st2 services have issues connecting to MongoDB it will show up in logs.

**Comment by vhristev** [comment]
Thank you now I see why process are looping. It seems working exit for some reason. 

```
root@b87e5a0666c2:/var/log/st2# head -200 st2api.log
[2019-05-09 10:37:20 +0000] [57] [INFO] Starting gunicorn 19.9.0
[2019-05-09 10:37:20 +0000] [57] [INFO] Listening at: http://127.0.0.1:9101 (57)
[2019-05-09 10:37:20 +0000] [57] [INFO] Using worker: eventlet
[2019-05-09 10:37:20 +0000] [321] [INFO] Booting worker with pid: 321
2019-05-09 10:37:23,498 140192884746048 INFO app [-] Creating st2api: StackStorm v3.0.0 as OpenAPI app.
2019-05-09 10:37:23,857 140192836488560 INFO __init__ [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-05-09 10:37:23,955 140192836488560 INFO __init__ [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
[2019-05-09 10:37:42 +0000] [321] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/wsgi.py", line 25, in <module>
    application = app.setup_app(config)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/app.py", line 80, in setup_app
    router.add_spec(spec, transforms=transforms)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 212, in add_spec
    __import__(module_name)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 437, in <module>
    key_value_pair_controller = KeyValuePairController()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 62, in __init__
    self._coordinator = coordination.get_coordinator()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 227, in get_coordinator
    COORDINATOR = coordinator_setup(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 200, in coordinator_setup
    coordinator.start(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 690, in start
    super(CoordinationDriverWithExecutor, self).start(start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 426, in start
    self._start()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 457, in _start
    self._server_info = self._client.info()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 51, in _translate_failures
    cause=e)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/utils.py", line 225, in raise_with_cause
    excutils.raise_with_cause(exc_cls, message, *args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_utils/excutils.py", line 143, in raise_with_cause
    six.raise_from(exc_cls(message, *args, **kwargs), kwargs.get('cause'))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ToozConnectionError: Error 111 connecting to localhost:6379. ECONNREFUSED.
[2019-05-09 10:37:42 +0000] [321] [INFO] Worker exiting (pid: 321)
2019-05-09 10:37:42,154 140192719340400 INFO mixins [-] Connected to amqp://admin:**@rabbitmq:5672//
[2019-05-09 10:37:44 +0000] [57] [INFO] Shutting down: Master
[2019-05-09 10:37:44 +0000] [57] [INFO] Reason: Worker failed to boot.
[2019-05-09 10:37:44 +0000] [592] [INFO] Starting gunicorn 19.9.0
[2019-05-09 10:37:44 +0000] [592] [INFO] Listening at: http://127.0.0.1:9101 (592)
[2019-05-09 10:37:44 +0000] [592] [INFO] Using worker: eventlet
[2019-05-09 10:37:44 +0000] [610] [INFO] Booting worker with pid: 610
2019-05-09 10:37:45,688 139945464084288 INFO app [-] Creating st2api: StackStorm v3.0.0 as OpenAPI app.
2019-05-09 10:37:45,734 139945415826800 INFO __init__ [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-05-09 10:37:45,751 139945415826800 INFO __init__ [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
2019-05-09 10:37:48,768 139945318540144 INFO mixins [-] Connected to amqp://admin:**@rabbitmq:5672//
[2019-05-09 10:37:48 +0000] [610] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/wsgi.py", line 25, in <module>
    application = app.setup_app(config)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/app.py", line 80, in setup_app
    router.add_spec(spec, transforms=transforms)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 212, in add_spec
    __import__(module_name)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 437, in <module>
    key_value_pair_controller = KeyValuePairController()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 62, in __init__
    self._coordinator = coordination.get_coordinator()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 227, in get_coordinator
    COORDINATOR = coordinator_setup(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 200, in coordinator_setup
    coordinator.start(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 690, in start
    super(CoordinationDriverWithExecutor, self).start(start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 426, in start
    self._start()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 457, in _start
    self._server_info = self._client.info()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 51, in _translate_failures
    cause=e)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/utils.py", line 225, in raise_with_cause
    excutils.raise_with_cause(exc_cls, message, *args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_utils/excutils.py", line 143, in raise_with_cause
    six.raise_from(exc_cls(message, *args, **kwargs), kwargs.get('cause'))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ToozConnectionError: Error 111 connecting to localhost:6379. ECONNREFUSED.
[2019-05-09 10:37:48 +0000] [610] [INFO] Worker exiting (pid: 610)
[2019-05-09 10:37:49 +0000] [592] [INFO] Shutting down: Master
[2019-05-09 10:37:49 +0000] [592] [INFO] Reason: Worker failed to boot.
[2019-05-09 10:37:49 +0000] [675] [INFO] Starting gunicorn 19.9.0
[2019-05-09 10:37:49 +0000] [675] [INFO] Listening at: http://127.0.0.1:9101 (675)
[2019-05-09 10:37:49 +0000] [675] [INFO] Using worker: eventlet
[2019-05-09 10:37:49 +0000] [690] [INFO] Booting worker with pid: 690
2019-05-09 10:37:50,387 139659735103296 INFO app [-] Creating st2api: StackStorm v3.0.0 as OpenAPI app.
2019-05-09 10:37:50,440 139659686845808 INFO __init__ [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-05-09 10:37:50,455 139659686845808 INFO __init__ [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
[2019-05-09 10:37:53 +0000] [690] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/wsgi.py", line 25, in <module>
    application = app.setup_app(config)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/app.py", line 80, in setup_app
    router.add_spec(spec, transforms=transforms)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 212, in add_spec
    __import__(module_name)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 437, in <module>
    key_value_pair_controller = KeyValuePairController()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 62, in __init__
    self._coordinator = coordination.get_coordinator()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 227, in get_coordinator
    COORDINATOR = coordinator_setup(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/coordination.py", line 200, in coordinator_setup
    coordinator.start(start_heart=start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 690, in start
    super(CoordinationDriverWithExecutor, self).start(start_heart)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 426, in start
    self._start()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 457, in _start
    self._server_info = self._client.info()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 51, in _translate_failures
    cause=e)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/utils.py", line 225, in raise_with_cause
    excutils.raise_with_cause(exc_cls, message, *args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_utils/excutils.py", line 143, in raise_with_cause
    six.raise_from(exc_cls(message, *args, **kwargs), kwargs.get('cause'))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ToozConnectionError: Error 111 connecting to localhost:6379. ECONNREFUSED.
[2019-05-09 10:37:53 +0000] [690] [INFO] Worker exiting (pid: 690)
2019-05-09 10:37:53,304 139659589546864 INFO mixins [-] Connected to amqp://admin:**@rabbitmq:5672//
[2019-05-09 10:37:55 +0000] [675] [INFO] Shutting down: Master
[2019-05-09 10:37:55 +0000] [675] [INFO] Reason: Worker failed to boot.
[2019-05-09 10:37:55 +0000] [719] [INFO] Starting gunicorn 19.9.0
[2019-05-09 10:37:55 +0000] [719] [INFO] Listening at: http://127.0.0.1:9101 (719)
[2019-05-09 10:37:55 +0000] [719] [INFO] Using worker: eventlet
[2019-05-09 10:37:55 +0000] [732] [INFO] Booting worker with pid: 732
2019-05-09 10:37:56,552 139899692857152 INFO app [-] Creating st2api: StackStorm v3.0.0 as OpenAPI app.
2019-05-09 10:37:56,610 139899644599664 INFO __init__ [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-05-09 10:37:56,627 139899644599664 INFO __init__ [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
[2019-05-09 10:37:59 +0000] [732] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
```

**Comment by armab** [comment]
It looks like coordination service in `st2.conf` which is `Redis` in this case is not configured properly. It tries to connect to `localhost:6379`.

Per https://github.com/StackStorm/st2-docker/blob/master/bin/write-env.sh#L47-L51 the connection string should be `redis:6379` instead.

Try to debug `make env` execution and see if `conf/redis.env` has the correct details.

**Comment by vhristev** [comment]
Thank you that is the problem I figure out its redis but I was searching how components are working to understand it better. 

Here is two different cases with MacOSX and Linux ( CentOS7 ) it seems make env is creating 'conf/redis.env' different way. I will try to figure out why. 

**Linux box after make env**
```
[root@RHCSA-server01 Data]# git clone https://github.com/StackStorm/st2-docker.git
Cloning into 'st2-docker'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1835 (delta 11), reused 26 (delta 7), pack-reused 1801
Receiving objects: 100% (1835/1835), 477.26 KiB | 447.00 KiB/s, done.
Resolving deltas: 100% (856/856), done.
[root@RHCSA-server01 Data]# cd st2-docker/
[root@RHCSA-server01 st2-docker]# make env
bin/write-env.sh conf
[root@RHCSA-server01 st2-docker]# cat conf/redis.env
REDIS_PASSWORD=L1AbVBM5yJ50+Kzrzhp7SEMh
REDIS_HOST=redis
REDIS_PORT=6379
[root@RHCSA-server01 st2-docker]# make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
**MacOSX box after make env:**
```
~/Desktop » git clone https://github.com/StackStorm/st2-docker.git                                                                                         vhristev@vhristev-a01
Cloning into 'st2-docker'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1835 (delta 11), reused 26 (delta 7), pack-reused 1801
Receiving objects: 100% (1835/1835), 477.26 KiB | 429.00 KiB/s, done.
Resolving deltas: 100% (856/856), done.
------------------------------------------------------------
~/Desktop » cd st2-docker                                                                                                                                  vhristev@vhristev-a01
------------------------------------------------------------
~/Desktop/st2-docker(master) » make env                                                                                                                    vhristev@vhristev-a01
bin/write-env.sh conf
------------------------------------------------------------
~/Desktop/st2-docker(master) » cat conf/redis.env                                                                                                          vhristev@vhristev-a01
REDIS_PASSWORD=JhyX5FayPd42vAMbzsMoFZLv
REDIS_HOST=localhost:6379
REDIS_PORT=6379
------------------------------------------------------------
~/Desktop/st2-docker(master) » make --version                                                                                                              vhristev@vhristev-a01
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by armab** [comment]
Cool, let us know your findings and hopefully fixes.

Per https://github.com/StackStorm/st2-docker/blob/master/bin/write-env.sh#L47 make sure `conf/redis.env` file doesn't exist before running `make env` and `REDIS_HOST` ENV var is unset.

**Comment by vhristev** [comment]
OK it seems you are using same var ENV name as I do for one of my other projects.  that's why other people cannot re-produce it consider it fixed we can close it and thank you for your help. 
```
st2-docker/conf(master*) » env | grep REDI                                                                        
REDIS_HOST=localhost:6379
```

**Comment by armab** [comment]
Glad we figured it out!
