### ISSUE TITLE
Problem installing or searching pack, temporary failure in name resolution

### ISSUE THREAD

**Issue by JustDevZero** [StackStorm/st2-docker#216]
**Describe the problem**
A clear and concise description of what the problem is.

**Versions**
 - Host OS: [e.g. Ubuntu 18.04]
 - docker: [e.g. 18.09.1-ce]
 - docker-compose: [e.g. 1.21.1]
 - stackstorm version: [e.g. v3.3.0]

**To Reproduce**
If necessary, please specify steps to reproduce the behavior.

Login to st2client with:

docker-compose exec st2client bash

And then try to search or install.

It will fail with:

```

st2 pack search datadog

root@554d99419ce3:/opt/stackstorm# st2 pack search docker
ERROR: 400 Client Error: Bad Request
MESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "packs": 0,
        "message": "ConnectionError(MaxRetryError(\"HTTPSConnectionPool(host='index.stackstorm.org', port=443): Max retries exceeded with url: /v1/index.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f448e565710>: Failed to establish a new connection: [Errno -3] Lookup timed out',))\",),)",
        "error": "unresponsive"
    }
] for url: http://st2api:9101/packs/index/search



root@554d99419ce3:/opt/stackstorm# st2 pack install datadog

	[ succeeded ] init_task
	[  failed   ] download_pack

id: 6038397af6cde4fdb05d5c08
action.ref: packs.install
parameters: 
  packs:
  - datadog
  python3: false
status: failed
start_timestamp: Thu, 25 Feb 2021 23:57:46 UTC
end_timestamp: Thu, 25 Feb 2021 23:57:59 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    result:
      exit_code: 1
      result: None
      stderr: "Index parsing error: {
    "url": "https://index.stackstorm.org/v1/index.json",
    "packs": 0,
    "message": "ConnectionError(MaxRetryError(\\"HTTPSConnectionPool(host='index.stackstorm.org', port=443): Max retries exceeded with url: /v1/index.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8ff5cdc18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))\\",),)",
    "error": "unresponsive"
}
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 334, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 193, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 90, in run
    return self._validate_result(result=result, repo_url=pack_url)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 111, in _validate_result
    raise Exception(message)
Exception: The pack has not been downloaded from "None".

Errors:
No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "packs": 0,
        "message": "ConnectionError(MaxRetryError(\\"HTTPSConnectionPool(host='index.stackstorm.org', port=443): Max retries exceeded with url: /v1/index.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8ff5cdc18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))\\",),)",
        "error": "unresponsive"
    }
]
"
      stdout: ''
    task_id: download_pack
    type: error
  output:
    conflict_list: null
    message: ''
    packs_list: null
    warning_list: null
+--------------------------+------------------------+---------------+----------------+-------------------------------+
| id                       | status                 | task          | action         | start_timestamp               |
+--------------------------+------------------------+---------------+----------------+-------------------------------+
| 6038397b1ac1577e7e12dae3 | succeeded (0s elapsed) | init_task     | core.noop      | Thu, 25 Feb 2021 23:57:47 UTC |
| 6038397c1ac1577e7e12daf3 | failed (11s elapsed)   | download_pack | packs.download | Thu, 25 Feb 2021 23:57:48 UTC |







```

If try to do some curl... from st2api container:

```

root@2bc662f52cab:/opt/stackstorm# curl https://index.stackstorm.org/v1/index.json|wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: index.stackstorm.org
0
```

Modifying resolve.conf for adding 1.1.1.1 after docker resolution improves the thing but still.

```

curl https://index.stackstorm.org/v1/index.json|wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  678k    0  678k    0     0   406k      0 --:--:--  0:00:02 --:--:--  406k
16298

```

From s2client container on the other hand it's inmediate.

```
curl https://index.stackstorm.org/v1/index.json|wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  678k    0  678k    0     0  3879k      0 --:--:-- --:--:-- --:--:-- 3857k
16298

```

For some reason, s2api container it's taking more time to resolv... But even with that it's no reason for getting a Temporary failure in name resolution.

**Comment by minsis** [comment]
By default bridge networks dont forward to the outside world and need to have additional parameters set on the host for this to work correctly.

https://docs.docker.com/network/bridge/#enable-forwarding-from-docker-containers-to-the-outside-world

**Comment by JustDevZero** [comment]
@minsis I tried it, and indeed also tried changing the type of network, but the problem is still the same.

**Comment by minsis** [comment]
@JustDevZero We also faced some of these issues (not with StackStorm) when ipv6 was enabled and ultimately disabled it. Do you also have ipv6 enabled?

**Comment by JustDevZero** [comment]
I'll check it as soon as I'm at my office hours, but I think you're maybe
having a point on the ipv6, AFAIK we have ipv6 disabled on whole network.

**Comment by minsis** [comment]
@JustDevZero The network itself can have ipv6 disabled as a whole but that doesn't prevent localhost from having it enabled. Every device has its own link local ipv6 address when it comes up.

**Comment by JustDevZero** [comment]
It looks that it's ipv6 fault then, host have ipv6 disabled but somehow docker it's still trying to get ipv6 not 4. So... I guess it's matter of dealing with docker config, maybe?

**Comment by daniel-rocha-ciandt** [comment]
Hi, 
I'm also facing the same issue, from curl it works perfectly.
![image](https://user-images.githubusercontent.com/6033757/132961832-01f6af0b-7387-4714-8245-981e704bb779.png)

Every action in python 3 that need to resolve a DNS happens the same problem:
![image](https://user-images.githubusercontent.com/6033757/132961944-f11fa4b2-5345-4fd0-bf10-0111219cbc06.png)

@JustDevZero  have you manager to find out what was the root cause of this issue? 

**Versions**

- Host OS: Ubuntu 20.04
- docker: Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1
- docker-compose version 1.29.1, build c34c88b2
- stackstorm version: v3.5.0
- Python: v3.6.9
