### ISSUE TITLE
can't install packs: use_python3 is unknown 

### ISSUE THREAD

**Issue by SorryGames** [StackStorm/st2-docker#230]
Good day!

##### Problem:
When installing packs in StackStorm v3.4.1 (repository with tag 3.4.1) there is the following error:

```
root@537ddb8451f8:/opt/stackstorm# st2 --version
st2 3.4.1, on Python 3.6.9
root@537ddb8451f8:/opt/stackstorm# st2 pack install fortinet

For the "fortinet" pack, the following content will be registered:

actions   |  13
rules     |  0
sensors   |  0
aliases   |  0
triggers  |  0

Installation may take a while for packs with many items.

	[ succeeded ] init_task
	[  failed   ] download_pack

id: 60d5c1dea92b634e2f601331
action.ref: packs.install
parameters: 
  packs:
  - fortinet
status: failed
start_timestamp: Fri, 25 Jun 2021 11:45:34 UTC
end_timestamp: Fri, 25 Jun 2021 11:45:37 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    result:
      exit_code: 1
      result: None
      stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 334, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 193, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 86, in run
    logger=self.logger)
TypeError: download_pack() got an unexpected keyword argument 'use_python3'
"
      stdout: ''
    task_id: download_pack
    type: error
  output:
    conflict_list: null
    message: ''
    packs_list: null
    warning_list: null
+--------------------------+------------------------+---------------+----------------+-------------------------------+
| id                       | status                 | task          | action         | start_timestamp               |
+--------------------------+------------------------+---------------+----------------+-------------------------------+
| 60d5c1df974be591fa75d50a | succeeded (0s elapsed) | init_task     | core.noop      | Fri, 25 Jun 2021 11:45:35 UTC |
| 60d5c1e0974be591fa75d51a | failed (1s elapsed)    | download_pack | packs.download | Fri, 25 Jun 2021 11:45:36 UTC |
+--------------------------+------------------------+---------------+----------------+-------------------------------+
root@537ddb8451f8:/opt/stackstorm# 
```

*P.S. with StackStorm v3.3.0 (actually, it's repository with tag 3.4.0) there is no problem to install packs.*

**Comment by winem** [comment]
I am a bit confused by the statement that v3.3.0 refers to the repo tag 3.4.0

`use_python3` is obsolete and was part of st2 < 3.4.0. 

So this looks like there may be an issue / conflict with the installed code after your upgrade? Did you restart all services or have you tried to reload and reregister everything, just to be sure?
