### ISSUE TITLE
st2-register-content traceback connecting to mongodb

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2-docker#42]
Following the Sensors troubleshooting guide...

root@56b83c8b706d:/# st2-register-content --register-sensors --register-fail-on-failure -v
2017-06-28 16:25:24,310 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2017-06-28 16:25:24,312 DEBUG [-] Ensuring database indexes...
2017-06-28 16:25:24,319 DEBUG [-] Ensuring indexes for model "UserDB"...
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 386, in main
    setup(argv)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 378, in setup
    common_setup(config=config, setup_db=True, register_mq_exchanges=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/script_setup.py", line 86, in setup
    db_setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/database_setup.py", line 43, in db_setup
    ssl_match_hostname=cfg.CONF.database.ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/db_init.py", line 65, in db_setup_with_retry
    ssl_match_hostname=ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 94, in db_setup
    db_ensure_indexes()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 137, in db_ensure_indexes
    raise exc_cls(msg)
pymongo.errors.ServerSelectionTimeoutError: Failed to ensure indexes for model "UserDB": 0.0.0.0:27017: [Errno 111] Connection refused

**Comment by LindsayHill** [comment]
Might need to add `--config-file /etc/st2/st2,conf` to get it to connect to right DB with right username/password?

**Comment by johnarnold** [comment]
If using docker-compose / following the directions, this should "just work"

**Comment by LindsayHill** [comment]
Assuming that what I suggested above is the right workaround, then it's not a Docker issue, it's a core issue - this is the one to track: https://github.com/StackStorm/st2/issues/3203
