### ISSUE TITLE
"Adding a rule" section appears to be outdated

### ISSUE THREAD

**Issue by dead10ck** [StackStorm/st2-docker#46]
The instructions in the "Adding a rule" section of the README does not appear to be correct. It instructs users to run:

```sh
echo "    - /tmp/date.log" >> /opt/stackstorm/packs/linux/config.yaml
st2ctl reload
```

But this `/opt/stackstorm/packs/linux/config.yaml` file does not exist. Additionally, after running `st2ctl reload`, there is an error:

```sh
root@03b58f3434ed:/# echo "    - /tmp/date.log" >> /opt/stackstorm/packs/linux/config.yaml
root@03b58f3434ed:/# st2ctl reload
Registering content...[flags = --config-file /etc/st2/st2.conf --register-runners --register-actions --register-aliases --register-sensors --register-triggers --register-configs --register-rules]
2017-07-07 14:56:37,688 INFO [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2017-07-07 14:56:37,772 INFO [-] =========================================================
2017-07-07 14:56:37,772 INFO [-] ############## Registering triggers #####################
2017-07-07 14:56:37,772 INFO [-] =========================================================
2017-07-07 14:56:37,800 WARNING [-] Pack "linux" contains a deprecated config.yaml file (/opt/stackstorm/packs/linux/config.yaml). Support for "config.yaml" files has been deprecated in StackStorm v1.6.0 in favor of config.schema.yaml config schema files and config files in /opt/stackstorm/configs/ directory.Support for config.yaml files will be removed in next major release  (v2.4.0) so you are strongly encouraged to migrate. For more information please refer to https://docs.stackstorm.com/reference/pack_configs.html 
2017-07-07 14:56:37,816 INFO [-] Registered 0 triggers.
2017-07-07 14:56:37,817 INFO [-] =========================================================
2017-07-07 14:56:37,817 INFO [-] ############## Registering sensors ######################
2017-07-07 14:56:37,817 INFO [-] =========================================================
2017-07-07 14:56:37,840 INFO [-] Registered 1 sensors.
2017-07-07 14:56:37,841 INFO [-] =========================================================
2017-07-07 14:56:37,841 INFO [-] ############## Registering runners ######################
2017-07-07 14:56:37,841 INFO [-] =========================================================
2017-07-07 14:56:38,059 INFO [-] Registered 13 runners.
2017-07-07 14:56:38,059 INFO [-] =========================================================
2017-07-07 14:56:38,059 INFO [-] ############## Registering actions ######################
2017-07-07 14:56:38,059 INFO [-] =========================================================
2017-07-07 14:56:38,922 INFO [-] Registered 52 actions.
2017-07-07 14:56:38,922 INFO [-] =========================================================
2017-07-07 14:56:38,922 INFO [-] ############## Registering rules ########################
2017-07-07 14:56:38,922 INFO [-] =========================================================
2017-07-07 14:56:38,970 WARNING [-] Failed to register rules: Failed to register rule "/opt/stackstorm/packs.dev/examples/rules/monitor_file.yaml" from pack "examples": A simple trigger should have been created when registering triggertype. Cannot create trigger: {'type': 'linux.file_watch.line', 'parameters': {}, 'pack': 'linux'}.
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 387, in main
    register_content()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 362, in register_content
    register_rules()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 248, in register_rules
    raise e
ValueError: Failed to register rule "/opt/stackstorm/packs.dev/examples/rules/monitor_file.yaml" from pack "examples": A simple trigger should have been created when registering triggertype. Cannot create trigger: {'type': 'linux.file_watch.line', 'parameters': {}, 'pack': 'linux'}.
##### st2 components status #####
st2actionrunner PID: 137
st2actionrunner PID: 145
st2actionrunner PID: 157
st2actionrunner PID: 161
st2api PID: 71
st2api PID: 240
st2stream PID: 73
st2stream PID: 223
st2auth PID: 62
st2auth PID: 230
st2garbagecollector PID: 60
st2notifier PID: 66
st2resultstracker PID: 64
st2rulesengine PID: 69
st2sensorcontainer PID: 59
st2chatops is not running.
mistral-server PID: 413
mistral-api PID: 405
mistral-api PID: 435
mistral-api PID: 436
```

**Comment by warrenvw** [comment]
@dead10ck thanks for submitting this issue. I've updated the README and `examples/rules/monitor_file.yaml` with a fix.
