### ISSUE TITLE
Kubernetes external port access

### ISSUE THREAD

**Issue by truck0321** [StackStorm/st2-docker#87]
I've added a nodeport to the st2web service to allow external access on port 30000.   I'm able to access the web interface but I get this error in the console:

`:30000/#/actions:1 WebSocket connection to 'wss://www.socked.io/app/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.`

Also,  attempting to install a pack fails with the below error in the console:

`VM426:1 POST https://server1:30000/api/v1/packs/install 400 (Bad Request)
(anonymous) @ VM426:1
xhrAdapter @ st2client.js:1167
(anonymous) @ st2client.js:1330
dispatchRequest @ st2client.js:1326
Promise resolved (async)
module.exports @ st2client.js:1210
request @ st2client.js:1006
value @ st2client.js:240
value @ st2client.js:684
handleInstall @ apps.js:3
onClick @ apps.js:3
r @ react.js:14
i @ react.js:12
u @ react.js:12
p @ react.js:12
f @ react.js:12
r @ react.js:15
processEventQueue @ react.js:12
r @ react.js:14
handleTopLevel @ react.js:14
i @ react.js:14
a @ react.js:14
perform @ react.js:15
batchedUpdates @ react.js:14
a @ react.js:15
dispatchEvent @ react.js:14
apps.js:3 {name: "APIError", status: 400, message: "Action "packs.install" cannot be found."}`

Here is the change I made to the service to add the nodeport (don't know how to format yaml,  apologies):

kind: Service
apiVersion: v1
metadata:
  name: st2web
spec:
  selector:
    app: st2web
  type: NodePort
  ports:
  - protocol: TCP
    port: 443
    nodePort: 30000

**Comment by shusugmt** [comment]
@truck0321 You can format multi-line content with surrounding ` ``` ` (three backticks)

It seems there are two separate problems here. I'm not sure what's causing the web socket error, but

> attempting to install a pack fails

Did you run these two jobs?
https://github.com/StackStorm/st2-docker/blob/master/runtime/kubernetes-1ppc/init-st2.yml

**Comment by truck0321** [comment]
Ahh,  I see now the the jobs are failing.   
 
init-st2-default-files fails with this error:
```
.f...p.g... packs/tests/fixtures/stackstorm-test2/pack.yaml
.d...p.g... packs/tests/fixtures/stackstorm-test3/
.f...p.g... packs/tests/fixtures/stackstorm-test3/pack.yaml
 sent 4,334 bytes  received 16,147 bytes  40,962.00 bytes/sec
total size is 146,950  speedup is 7.17
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
```

init-st2-register-content failed with this error:
```
2017-12-18 17:49:48,105 INFO [-] =========================================================
2017-12-18 17:49:48,105 INFO [-] ############## Registering configs ######################
2017-12-18 17:49:48,105 INFO [-] =========================================================
2017-12-18 17:49:48,105 INFO [-] Registered 0 configs.
2017-12-18 17:49:48,105 INFO [-] =========================================================
2017-12-18 17:49:48,106 INFO [-] ########### Setting up virtual environments #############
2017-12-18 17:49:48,106 INFO [-] =========================================================
2017-12-18 17:49:48,118 WARNING [-] Failed to setup virtualenv for pack "chatops": [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 388, in main
    register_content()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 374, in register_content
    setup_virtualenvs()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 121, in setup_virtualenvs
    raise e
OSError: [Errno 2] No such file or directory
```

**Comment by truck0321** [comment]
Figured this out.  I had configured one NFS share to use for st2-packs and st2-virtualenvs.  No subfolder was created by the config to distinguish the 2 locations.   Since the folder structure is the same for both volume mounts,  st2-virtualenvs was not being created and anything that needed it failed (i.e. installing packs)
